config:
  azure-native:location: UkSouth
  bk-portal-site:gh_token:
    secure: AAABAEe2e6Z4RiFCii3UAAm6QWQdmLYQ/VomMxpXo8TbGAjYtcDJdLHMlfnix/JIxwHv5HpRyBQW0Xr5NSmCzydB63SxcdReG3SV2m6X8jWJgGQ9CGhof6ibflnyZUhPOnMHcWHLIOue1RJlG/MSpEb4aPn4dgimg8W8q+I=
